use_frameworks!

target 'Brocade_Example' do
  pod 'Brocade', :path => '../'

  target 'Brocade_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.0'
    pod 'Nimble', '9.0.0-rc.1'
  end
end
