# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile

before_install:
- export IOS_SIMULATOR_DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.3"
- gem install cocoapods
#- pod install --project-directory=Example

before_script:
  - set -o pipefail

script:
xcodebuild -workspace Example/Brocade.xcworkspace -scheme Brocade-Example -sdk iphonesimulator -destination "$IOS_SIMULATOR_DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
# - xcodebuild test -enableCodeCoverage YES -workspace Example/Brocade.xcworkspace -scheme Brocade-Example -sdk "$IOS_SIMULATOR_DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
